Missing ifdef causing compilation issue.  Fixed
Compilation throw error:
```
drivers/amlogic/ethernet/am_net8218.c:1473:2: error: unknown field 'ndo_poll_controller' specified in initializer
  .ndo_poll_controller = fake_netpoll,
  ^
drivers/amlogic/ethernet/am_net8218.c:1473:25: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
  .ndo_poll_controller = fake_netpoll,
                         ^~~~~~~~~~~~
drivers/amlogic/ethernet/am_net8218.c:1473:25: note: (near initialization for 'am_netdev_ops.ndo_do_ioctl')
```

This declaration depends on CONFIG_NET_POOL_CONTROLLER, the `#ifdef` solves the compilation issue.