ODROID: fix compile error for missing header
In file included from /opt/source/media_modules/drivers/frame_provider/decoder/utils/../../../amvdec_ports/aml_vcodec_drv.h:39,
                 from /opt/source/media_modules/drivers/frame_provider/decoder/utils/vdec.c:87:
/opt/source/media_modules/drivers/frame_provider/decoder/utils/../../../amvdec_ports/aml_vcodec_util.h:35:10: fatal error: linux/amlogic/media/codec_mm/codec_mm_prealloc.h: No such file or directory
   35 | #include <linux/amlogic/media/codec_mm/codec_mm_prealloc.h>
      |

Signed-off-by: Dongjin Kim <tobetter@gmail.com>
Change-Id: I750814e9c3c00e97e206df0db47c994cfcfe26e4